### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by trim21** [goccy/go-reflect#15]
I'm trying to use this package, But I'm using goland and struggle with the problem fixed in this commit https://github.com/goccy/go-reflect/commit/b725637422e43c3e5556f930b7f5c0d592d0dbaa.

can you create a new release?

**Comment by trim21** [comment]
And, I just write a package from your `benchmark_marshaler_test.go`, I'd like to add example about slice, map(zero allocation iteration). would you accept a PR for this?

**Comment by goccy** [comment]
Thank you for the contribution ! I just released a new version as v1.2.0 .

> I'd like to add example about slice, map(zero allocation iteration). would you accept a PR for this?

Yes, Contributions are welcome !

**Comment by trim21** [comment]
I'm reading your source in go-json and I have a question about your decoder, 

I find that most decoder are end with `for{ switch {} }`. some decoder need that `for{}` but also some types (like bool decoder) don't need them also have this for loop.

Is this a performance tech to trick compiler or just for code style?
